# Generated by Django 4.2.24 on 2025-10-17 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('valuating', 'Valuating'), ('negotiating', 'Negotiating'), ('closed', 'Closed')], default='valuating', max_length=20)),
                ('scheduled_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('license_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('capturing', 'Capturing'), ('validating', 'Validating'), ('marketing', 'Marketing'), ('closed', 'Closed')], default='capturing', max_length=20)),
                ('probability', models.PositiveSmallIntegerField(default=0, help_text='Likelihood (0-100) of closing the opportunity.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.agent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_opportunities', to='core.contact')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('reference_code', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('preparing', 'Preparing'), ('presented', 'Presented'), ('accepted', 'Accepted')], default='preparing', max_length=20)),
                ('presented_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='core.opportunity')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_reviews', to='core.agent')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.property'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('offered', 'Offered'), ('reinforced', 'Reinforced'), ('closed', 'Closed')], default='offered', max_length=20)),
                ('offered_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount proposed in this negotiation step.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserve_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Remaining reserved funds after this step.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reinforcement_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Additional funds available for reinforcement, if applicable.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='core.currency')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.opportunity')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactAgentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('former', 'Former')], default='active', max_length=20)),
                ('relationship_notes', models.TextField(blank=True)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='core.agent')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_links', to='core.contact')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('agent', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('evaluated_at', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('external_report_url', models.URLField(blank=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal', to='core.acquisitionattempt')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='core.currency')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='agents', through='core.ContactAgentRelationship', to='core.contact'),
        ),
        migrations.AddField(
            model_name='acquisitionattempt',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisition_assignments', to='core.agent'),
        ),
        migrations.AddField(
            model_name='acquisitionattempt',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_attempts', to='core.opportunity'),
        ),
        migrations.CreateModel(
            name='MarketingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('preparing', 'Preparing'), ('available', 'Available'), ('paused', 'Paused')], default='preparing', max_length=20)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('features', models.JSONField(blank=True, default=list, help_text='Key property highlights or amenities.')),
                ('media_assets', models.JSONField(blank=True, default=list, help_text='List of image or video asset URLs.')),
                ('effort_type', models.CharField(choices=[('general', 'General'), ('digital', 'Digital'), ('events', 'Events'), ('print', 'Print'), ('other', 'Other')], default='general', max_length=20)),
                ('campaign_start', models.DateField(blank=True, null=True)),
                ('campaign_end', models.DateField(blank=True, null=True)),
                ('marketing_notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_packages', to='core.currency')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_packages', to='core.opportunity')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('opportunity', 'version')},
            },
        ),
    ]
