# Generated by Django 4.2.24 on 2025-10-17 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_agent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='valuation_currency',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='opportunityoperation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_operations', to='core.currency'),
        ),
    ]
