# Generated by Django 4.2.24 on 2025-10-17 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency_remove_appraisal_valuation_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunityoperation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='opportunityoperation',
            name='related_operation',
        ),
        migrations.AddField(
            model_name='opportunityoperation',
            name='offered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount proposed in this negotiation step.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='opportunityoperation',
            name='reinforcement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional funds available for reinforcement, if applicable.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='opportunityoperation',
            name='reserve_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining reserved funds after this step.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
