# Generated by Django 4.2.24 on 2025-10-17 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_opportunityoperation_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listing',
            name='campaign_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='campaign_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='effort_type',
            field=models.CharField(choices=[('general', 'General'), ('digital', 'Digital'), ('events', 'Events'), ('print', 'Print'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Key property highlights or amenities.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='marketing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='media_assets',
            field=models.JSONField(blank=True, default=list, help_text='List of image or video asset URLs.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='asking_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listed_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
    ]
