# Generated by Django 4.2.24 on 2025-11-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_contact_full_name_email_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='reference_code',
        ),
    ]
