# Generated by Django 4.2.24 on 2025-10-17 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_listing_unique_together_listing_campaign_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('features', models.JSONField(blank=True, default=list)),
                ('media_assets', models.JSONField(blank=True, default=list)),
                ('effort_type', models.CharField(choices=[('general', 'General'), ('digital', 'Digital'), ('events', 'Events'), ('print', 'Print'), ('other', 'Other')], default='general', max_length=20)),
                ('campaign_start', models.DateField(blank=True, null=True)),
                ('campaign_end', models.DateField(blank=True, null=True)),
                ('marketing_notes', models.TextField(blank=True)),
                ('performance_metrics', models.JSONField(blank=True, default=dict, help_text='Arbitrary metrics captured for this marketing iteration.')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_snapshots', to='core.agent')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_snapshots', to='core.currency')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.listing')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
