# Generated by Django 4.2.24 on 2025-10-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_listingsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together={('opportunity', 'version')},
        ),
        migrations.DeleteModel(
            name='ListingSnapshot',
        ),
    ]
