# Generated by Codex on 2025-10-17
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_listing_is_active_listing_version_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='MarketingPackage',
        ),
        migrations.AlterField(
            model_name='marketingpackage',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_packages', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='marketingpackage',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_packages', to='core.opportunity'),
        ),
    ]
