# Generated by Django 4.2.24 on 2026-01-16 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonapropPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting_id', models.PositiveBigIntegerField(unique=True)),
                ('internal_code', models.CharField(max_length=64)),
                ('begin_date', models.DateField()),
                ('status', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('listing_payload', models.JSONField()),
                ('summary_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Zonaprop publication',
                'verbose_name_plural': 'Zonaprop publications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ZonapropPublicationDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField()),
                ('views', models.PositiveIntegerField()),
                ('leads', models.PositiveIntegerField()),
                ('user_stats', models.JSONField(default=dict)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='integrations.zonaproppublication')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddConstraint(
            model_name='zonaproppublicationdailystat',
            constraint=models.UniqueConstraint(fields=('publication', 'date'), name='unique_zonaprop_publication_day'),
        ),
    ]
