# Generated by Django 4.2.24 on 2026-01-16 06:06

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_zonaproppublication_zonaproppublicationdailystat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonaproppublication',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='zonaproppublication',
            name='status',
        ),
        migrations.AddField(
            model_name='zonaproppublication',
            name='state',
            field=django_fsm.FSMField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20),
        ),
    ]
