# Generated by Django 4.2.24 on 2026-01-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_remove_zonaproppublication_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaproppublication',
            name='publisher_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
