# Generated by Django 4.2.24 on 2026-01-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_zonaproppublication_publisher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonaproppublication',
            name='summary_payload',
        ),
    ]
