# Generated by Django 4.2 on 2026-01-16

from django.db import migrations, models


def _backfill_publisher_id(apps, schema_editor):
    ZonapropPublication = apps.get_model("integrations", "ZonapropPublication")
    for publication in ZonapropPublication.objects.filter(publisher_id__isnull=True):
        payload = publication.listing_payload or {}
        publisher_id = payload.get("publisherId")
        if not isinstance(publisher_id, int):
            raise RuntimeError(
                f"Missing publisherId for publication {publication.posting_id}"
            )
        publication.publisher_id = publisher_id
        publication.save(update_fields=["publisher_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0005_remove_zonaproppublication_summary_payload"),
    ]

    operations = [
        migrations.RunPython(_backfill_publisher_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="zonaproppublication",
            name="publisher_id",
            field=models.PositiveBigIntegerField(),
        ),
    ]

