# Generated by Django 4.2 on 2026-01-16

from django.db import migrations, models


def _backfill_status(apps, schema_editor):
    ZonapropPublication = apps.get_model("integrations", "ZonapropPublication")
    for publication in ZonapropPublication.objects.all():
        status = None
        payload = publication.listing_payload or {}
        state_and_dates = payload.get("stateAndDates")
        if isinstance(state_and_dates, list) and state_and_dates:
            status = state_and_dates[0].get("status")
        if not status:
            raw_state = getattr(publication, "state", None)
            if raw_state == "online":
                status = "ONLINE"
            elif raw_state == "offline":
                status = "OFFLINE"
        if not status:
            raise RuntimeError(
                f"Missing status for publication {publication.posting_id}"
            )
        publication.status = status
        publication.save(update_fields=["status"])


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0006_zonaproppublication_publisher_id_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonaproppublication",
            name="status",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.RunPython(_backfill_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="zonaproppublication",
            name="status",
            field=models.CharField(max_length=32),
        ),
        migrations.RemoveField(
            model_name="zonaproppublication",
            name="state",
        ),
    ]

