# Generated by Django 4.2 on 2026-01-16

from django.db import migrations, models


def _backfill_posting_url(apps, schema_editor):
    ZonapropPublication = apps.get_model("integrations", "ZonapropPublication")
    for publication in ZonapropPublication.objects.all():
        payload = publication.listing_payload or {}
        url_posting = payload.get("urlPosting")
        if not isinstance(url_posting, str) or not url_posting:
            raise RuntimeError(
                f"Missing urlPosting for publication {publication.posting_id}"
            )
        if url_posting.startswith("http"):
            posting_url = url_posting
        else:
            posting_url = (
                "https://www.zonaprop.com.ar/propiedades/clasificado/"
                f"{url_posting.lstrip('/')}"
            )
        publication.posting_url = posting_url
        publication.save(update_fields=["posting_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0007_zonaproppublication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonaproppublication",
            name="posting_url",
            field=models.URLField(null=True),
        ),
        migrations.RunPython(_backfill_posting_url, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="zonaproppublication",
            name="posting_url",
            field=models.URLField(),
        ),
    ]

