# Generated by Django 4.2.24 on 2025-11-14 09:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import intentions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProviderIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('assessing', 'Assessing'), ('valuated', 'Valuated'), ('contract_negotiation', 'Contract Negotiation'), ('converted', 'Converted'), ('withdrawn', 'Withdrawn')], default='assessing', max_length=32)),
                ('contract_signed_on', models.DateField(blank=True, null=True)),
                ('documentation_notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('withdraw_reason', models.CharField(blank=True, choices=[('lack_commitment', 'Not truly committed'), ('cannot_sell', 'Unable to sell (documentation/legal)')], max_length=32)),
            ],
            options={
                'verbose_name': 'sale provider intention',
                'verbose_name_plural': 'sale provider intentions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_valuations', to='core.agent')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_valuations', to='core.currency')),
                ('provider_intention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='intentions.saleproviderintention')),
            ],
            options={
                'verbose_name': 'sale valuation',
                'verbose_name_plural': 'sale valuations',
                'ordering': ('-delivered_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SaleSeekerIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('qualifying', 'Qualifying'), ('active', 'Active Search'), ('mandated', 'Mandated'), ('converted', 'Converted'), ('abandoned', 'Abandoned')], default='qualifying', max_length=32)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('desired_features', models.JSONField(blank=True, default=intentions.models._default_feature_map)),
                ('notes', models.TextField(blank=True)),
                ('search_activated_at', models.DateTimeField(blank=True, null=True)),
                ('mandate_signed_on', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_seeker_intentions', to='core.agent')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_seeker_intentions', to='core.contact')),
            ],
            options={
                'verbose_name': 'sale seeker intention',
                'verbose_name_plural': 'sale seeker intentions',
                'ordering': ('-created_at',),
            },
        ),
    ]
