# Generated by Django 4.2.24 on 2025-11-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('intentions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleseekerintention',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency'),
        ),
        migrations.AddField(
            model_name='saleproviderintention',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_provider_intentions', to='core.agent'),
        ),
        migrations.AddField(
            model_name='saleproviderintention',
            name='valuation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='intentions.salevaluation'),
        ),
        migrations.AddField(
            model_name='saleproviderintention',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_provider_intentions', to='core.contact'),
        ),
        migrations.AddField(
            model_name='saleproviderintention',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_provider_intentions', to='core.property'),
        ),
    ]
