# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations
import django_fsm


def drop_contract_negotiation_state(apps, schema_editor):
    SaleProviderIntention = apps.get_model("intentions", "SaleProviderIntention")
    SaleProviderIntention.objects.filter(state="contract_negotiation").update(state="valuated")


class Migration(migrations.Migration):

    dependencies = [
        ("intentions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleproviderintention",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("assessing", "Assessing"),
                    ("valuated", "Valuated"),
                    ("converted", "Converted"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="assessing",
                max_length=32,
                protected=False,
            ),
        ),
        migrations.RunPython(drop_contract_negotiation_state, migrations.RunPython.noop),
    ]
