# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations, models
import django.db.models.deletion


def set_default_operation_type(apps, schema_editor):
    OperationType = apps.get_model("opportunities", "OperationType")
    default = OperationType.objects.filter(code="sale").first()
    ProviderIntention = apps.get_model("intentions", "SaleProviderIntention")
    SeekerIntention = apps.get_model("intentions", "SaleSeekerIntention")
    if default:
        ProviderIntention.objects.filter(operation_type__isnull=True).update(operation_type=default)
        SeekerIntention.objects.filter(operation_type__isnull=True).update(operation_type=default)


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0014_operation_type_model"),
        ("intentions", "0003_remove_contract_negotiation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleproviderintention",
            name="operation_type",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="provider_intentions", to="opportunities.operationtype"),
        ),
        migrations.AddField(
            model_name="saleseekerintention",
            name="operation_type",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="seeker_intentions", to="opportunities.operationtype"),
        ),
        migrations.RunPython(set_default_operation_type, migrations.RunPython.noop),
    ]
