# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0015_replace_operation_state_with_type"),
        ("intentions", "0004_add_operation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleproviderintention",
            name="operation_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="provider_intentions", to="opportunities.operationtype"),
        ),
        migrations.AlterField(
            model_name="saleseekerintention",
            name="operation_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="seeker_intentions", to="opportunities.operationtype"),
        ),
    ]
