# Generated by Django 4.2.24 on 2025-12-12 08:46

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0011_salevaluation_test_close_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleseekerintention',
            name='mandate_signed_on',
        ),
        migrations.RemoveField(
            model_name='saleseekerintention',
            name='search_activated_at',
        ),
        migrations.AlterField(
            model_name='saleseekerintention',
            name='state',
            field=django_fsm.FSMField(choices=[('qualifying', 'Qualifying'), ('converted', 'Converted'), ('abandoned', 'Abandoned')], default='qualifying', max_length=32),
        ),
    ]
