# Generated by Django 4.2.24 on 2025-12-12 12:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_fsm
import intentions.models
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0012_remove_saleseekerintention_mandate_signed_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('assessing', 'Assessing'), ('valuated', 'Valuated'), ('converted', 'Converted'), ('withdrawn', 'Withdrawn')], default='assessing', max_length=32)),
                ('contract_signed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('withdraw_reason', models.CharField(blank=True, choices=[('lack_commitment', 'Not truly committed'), ('cannot_sell', 'Unable to sell (documentation/legal)')], max_length=32)),
            ],
            options={
                'verbose_name': 'provider intention',
                'verbose_name_plural': 'provider intentions',
                'ordering': ('-created_at',),
            },
            bases=(utils.mixins.FSMTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SeekerIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('qualifying', 'Qualifying'), ('converted', 'Converted'), ('abandoned', 'Abandoned')], default='qualifying', max_length=32)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('desired_features', models.JSONField(blank=True, default=intentions.models._default_feature_map)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'seeker intention',
                'verbose_name_plural': 'seeker intentions',
                'ordering': ('-created_at',),
            },
            bases=(utils.mixins.FSMTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('test_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('close_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valuation_date', models.DateField(blank=True, help_text='Date the valuation was issued.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'valuation',
                'verbose_name_plural': 'valuations',
                'ordering': ('-delivered_at', '-created_at'),
            },
        ),
        migrations.RemoveField(
            model_name='saleproviderintention',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='saleproviderintention',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='saleproviderintention',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='saleproviderintention',
            name='property',
        ),
        migrations.RemoveField(
            model_name='saleproviderintention',
            name='valuation',
        ),
        migrations.RemoveField(
            model_name='saleseekerintention',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='saleseekerintention',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='saleseekerintention',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='saleseekerintention',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='salevaluation',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='salevaluation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='salevaluation',
            name='provider_intention',
        ),
    ]
