# Generated by Django 4.2.24 on 2025-12-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0044_alter_provideropportunity_source_intention_and_more'),
        ('core', '0008_contact_phone_nullable'),
        ('intentions', '0013_providerintention_seekerintention_valuation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleProviderIntention',
        ),
        migrations.DeleteModel(
            name='SaleSeekerIntention',
        ),
        migrations.DeleteModel(
            name='SaleValuation',
        ),
        migrations.AddField(
            model_name='valuation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuations', to='core.agent'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuations', to='core.currency'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='provider_intention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='intentions.providerintention'),
        ),
        migrations.AddField(
            model_name='seekerintention',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seeker_intentions', to='core.agent'),
        ),
        migrations.AddField(
            model_name='seekerintention',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seeker_intentions', to='core.contact'),
        ),
        migrations.AddField(
            model_name='seekerintention',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency'),
        ),
        migrations.AddField(
            model_name='seekerintention',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seeker_intentions', to='opportunities.operationtype'),
        ),
        migrations.AddField(
            model_name='providerintention',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_intentions', to='core.agent'),
        ),
        migrations.AddField(
            model_name='providerintention',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_intentions', to='opportunities.operationtype'),
        ),
        migrations.AddField(
            model_name='providerintention',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_intentions', to='core.contact'),
        ),
        migrations.AddField(
            model_name='providerintention',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_intentions', to='core.property'),
        ),
        migrations.AddField(
            model_name='providerintention',
            name='valuation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='intentions.valuation'),
        ),
    ]
