# Generated by Django 4.2.24 on 2026-01-15 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0014_delete_saleproviderintention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuation',
            name='amount',
        ),
        migrations.AddField(
            model_name='providerintention',
            name='intention_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='seekerintention',
            name='intention_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
