# Generated by Django 4.2.24 on 2025-11-14 08:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('valuating', 'Valuating'), ('negotiating', 'Negotiating'), ('closed', 'Closed')], default='valuating', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'acquisition attempt',
                'verbose_name_plural': 'acquisition attempts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('state', django_fsm.FSMField(choices=[('capturing', 'Capturing'), ('validating', 'Validating'), ('marketing', 'Marketing'), ('closed', 'Closed')], default='capturing', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.agent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_opportunities', to='core.contact')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.property')),
            ],
            options={
                'verbose_name': 'opportunity',
                'verbose_name_plural': 'opportunities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('preparing', 'Preparing'), ('presented', 'Presented'), ('accepted', 'Accepted')], default='preparing', max_length=20)),
                ('presented_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'validation',
                'verbose_name_plural': 'validations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('offered', 'Offered'), ('reinforced', 'Reinforced'), ('closed', 'Closed')], default='offered', max_length=20)),
                ('offered_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount proposed in this negotiation step.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserve_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Remaining reserved funds after this step.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reinforcement_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Additional funds available for reinforcement, if applicable.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='core.currency')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'operation',
                'verbose_name_plural': 'operations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MarketingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('preparing', 'Preparing'), ('available', 'Available'), ('paused', 'Paused')], default='preparing', max_length=20)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('features', models.JSONField(blank=True, default=list, help_text='Key property highlights or amenities.')),
                ('media_assets', models.JSONField(blank=True, default=list, help_text='List of image or video asset URLs.')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_packages', to='core.currency')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_packages', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'marketing package',
                'verbose_name_plural': 'marketing packages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('evaluated_at', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('external_report_url', models.URLField(blank=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal', to='opportunities.acquisitionattempt')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='core.currency')),
            ],
            options={
                'verbose_name': 'appraisal',
                'verbose_name_plural': 'appraisals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='acquisitionattempt',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_attempts', to='opportunities.opportunity'),
        ),
    ]
