# Generated by Django 4.2.24 on 2025-10-17 13:49

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitionattempt',
            name='state',
            field=django_fsm.FSMField(choices=[('valuating', 'Valuating'), ('negotiating', 'Negotiating'), ('closed', 'Closed')], default='valuating', max_length=20, protected=False),
        ),
        migrations.AlterField(
            model_name='marketingpackage',
            name='state',
            field=django_fsm.FSMField(choices=[('preparing', 'Preparing'), ('available', 'Available'), ('paused', 'Paused')], default='preparing', max_length=20, protected=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='state',
            field=django_fsm.FSMField(choices=[('offered', 'Offered'), ('reinforced', 'Reinforced'), ('closed', 'Closed')], default='offered', max_length=20, protected=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='state',
            field=django_fsm.FSMField(choices=[('capturing', 'Capturing'), ('validating', 'Validating'), ('marketing', 'Marketing'), ('closed', 'Closed')], default='capturing', max_length=20, protected=False),
        ),
        migrations.AlterField(
            model_name='validation',
            name='state',
            field=django_fsm.FSMField(choices=[('preparing', 'Preparing'), ('presented', 'Presented'), ('accepted', 'Accepted')], default='preparing', max_length=20, protected=False),
        ),
    ]
