# Generated by Django 4.2.24 on 2025-11-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideropportunity',
            name='title',
        ),
        migrations.RemoveField(
            model_name='seekeropportunity',
            name='title',
        ),
    ]
