# Generated by Django 4.2.24 on 2025-11-14 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0002_remove_provideropportunity_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='validation_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_validation_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_validation_documents', to=settings.AUTH_USER_MODEL)),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='opportunities.validation')),
            ],
            options={
                'verbose_name': 'validation document',
                'verbose_name_plural': 'validation documents',
                'ordering': ('-created_at',),
            },
        ),
    ]
