# Generated by Django 4.2.24 on 2025-10-31 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_acquisitionattempt_state_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketingpackage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='acquisitionattempt',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='acquisitionattempt',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='license_id',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='budget_amount',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='expected_close_date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='source',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='marketingpackage',
            name='campaign_end',
        ),
        migrations.RemoveField(
            model_name='marketingpackage',
            name='campaign_start',
        ),
        migrations.RemoveField(
            model_name='marketingpackage',
            name='effort_type',
        ),
        migrations.RemoveField(
            model_name='marketingpackage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='marketingpackage',
            name='marketing_notes',
        ),
        migrations.RemoveField(
            model_name='marketingpackage',
            name='version',
        ),
    ]
