# Generated by Django 4.2.24 on 2025-10-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_alter_marketingpackage_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokkobrokerProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tokko_id', models.PositiveIntegerField(unique=True)),
                ('ref_code', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('tokko_created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tokkobroker property',
                'verbose_name_plural': 'Tokkobroker properties',
                'ordering': ('-created_at',),
            },
        ),
    ]
