# Generated by Django 4.2.24 on 2025-11-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_validationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationdocument',
            name='document_type',
            field=models.CharField(choices=[('property_title', 'Property Title'), ('identification', 'Identification Document'), ('tax_clearance', 'Tax Clearance Certificate'), ('other', 'Other Supporting Document')], default='other', max_length=50),
        ),
    ]
