# Generated by Django 4.2.24 on 2025-11-14 12:21

from django.db import migrations, models


OLD_TO_NEW = {
    'property_title': 'deed',
    'identification': 'owner_id',
    'tax_clearance': 'domain_report',
}


def forwards(apps, schema_editor):
    ValidationDocument = apps.get_model('opportunities', 'ValidationDocument')
    for old, new in OLD_TO_NEW.items():
        ValidationDocument.objects.filter(document_type=old).update(document_type=new)


def backwards(apps, schema_editor):
    new_to_old = {v: k for k, v in OLD_TO_NEW.items()}
    ValidationDocument = apps.get_model('opportunities', 'ValidationDocument')
    for new_value, old_value in new_to_old.items():
        ValidationDocument.objects.filter(document_type=new_value).update(document_type=old_value)
    ValidationDocument.objects.filter(document_type='sale_authorization').update(document_type='property_title')


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_validationdocument_document_type'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='validationdocument',
            name='document_type',
            field=models.CharField(choices=[('owner_id', 'DNI PROPIETARIO'), ('deed', 'ESCRITURA'), ('sale_authorization', 'AUTORIZACIÓN DE VENTA'), ('domain_report', 'INFORME DE DOMINIO'), ('other', 'OTRO DOCUMENTO')], default='other', max_length=50),
        ),
    ]
