# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations
import django_fsm


def promote_capturing_to_validating(apps, schema_editor):
    ProviderOpportunity = apps.get_model("opportunities", "ProviderOpportunity")
    ProviderOpportunity.objects.filter(state="capturing").update(state="validating")


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0008_rename_marketing_package_states"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provideropportunity",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("validating", "Validating"),
                    ("marketing", "Marketing"),
                    ("closed", "Closed"),
                ],
                default="validating",
                max_length=20,
                protected=False,
            ),
        ),
        migrations.RunPython(promote_capturing_to_validating, migrations.RunPython.noop),
    ]
