# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0009_remove_capturing_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="validationdocument",
            old_name="name",
            new_name="observations",
        ),
        migrations.AlterField(
            model_name="validationdocument",
            name="observations",
            field=models.TextField(blank=True),
        ),
    ]
