# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations, models


def seed_document_types(apps, schema_editor):
    DocType = apps.get_model("opportunities", "ValidationDocumentType")
    # Required defaults
    DocType.objects.update_or_create(code="owner_id", defaults={"label": "DNI PROPIETARIO", "required": True})
    DocType.objects.update_or_create(code="deed", defaults={"label": "ESCRITURA", "required": True})
    DocType.objects.update_or_create(code="sale_authorization", defaults={"label": "AUTORIZACIÓN DE VENTA", "required": True})
    DocType.objects.update_or_create(code="domain_report", defaults={"label": "INFORME DE DOMINIO", "required": True})
    # Optional catch-all
    DocType.objects.update_or_create(code="other", defaults={"label": "OTRO DOCUMENTO", "required": False})


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0010_replace_name_with_observations"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationDocumentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=150)),
                ("required", models.BooleanField(default=False)),
                ("operation_state", models.CharField(
                    max_length=20, blank=True, null=True,
                    choices=[
                        ("offered", "Offered"),
                        ("reinforced", "Reinforced"),
                        ("closed", "Closed"),
                        ("lost", "Lost"),
                    ],
                    help_text="Apply this document requirement only for the specified operation state; leave blank for all."
                )),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.RunPython(seed_document_types, migrations.RunPython.noop),
    ]
