# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations, models
import django.db.models.deletion


def migrate_document_types(apps, schema_editor):
    ValidationDocument = apps.get_model("opportunities", "ValidationDocument")
    DocType = apps.get_model("opportunities", "ValidationDocumentType")
    for doc in ValidationDocument.objects.all():
        try:
            dtype = DocType.objects.get(code=doc.document_type_old)
        except DocType.DoesNotExist:
            dtype = DocType.objects.filter(code="other").first()
        doc.document_type_fk_id = dtype.id if dtype else None
        doc.save(update_fields=["document_type_fk_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0011_document_type_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationdocument",
            name="document_type_fk",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="opportunities.validationdocumenttype"),
        ),
        migrations.RenameField(
            model_name="validationdocument",
            old_name="document_type",
            new_name="document_type_old",
        ),
        migrations.RunPython(migrate_document_types, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="validationdocument",
            name="document_type_old",
        ),
        migrations.RenameField(
            model_name="validationdocument",
            old_name="document_type_fk",
            new_name="document_type",
        ),
    ]
