# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations, models
import django.db.models.deletion


def fill_missing_doc_types(apps, schema_editor):
    ValidationDocument = apps.get_model("opportunities", "ValidationDocument")
    DocType = apps.get_model("opportunities", "ValidationDocumentType")
    fallback = DocType.objects.filter(code="other").first()
    if not fallback:
        fallback = DocType.objects.create(code="other", label="Other document", required=False)
    ValidationDocument.objects.filter(document_type__isnull=True).update(document_type=fallback)


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0012_convert_document_type_fk"),
    ]

    operations = [
        migrations.RunPython(fill_missing_doc_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="validationdocument",
            name="document_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="opportunities.validationdocumenttype"),
        ),
    ]
