# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations, models


def seed_operation_types(apps, schema_editor):
    OperationType = apps.get_model("opportunities", "OperationType")
    OperationType.objects.update_or_create(code="sale", defaults={"label": "Sale"})
    OperationType.objects.update_or_create(code="rent", defaults={"label": "Rent"})


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0013_finalize_document_type_fk"),
        ("intentions", "0003_remove_contract_negotiation_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
            options={"ordering": ("code",)},
        ),
        migrations.RunPython(seed_operation_types, migrations.RunPython.noop),
    ]
