# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations, models
import django.db.models.deletion


def map_operation_type(apps, schema_editor):
    DocType = apps.get_model("opportunities", "ValidationDocumentType")
    OperationType = apps.get_model("opportunities", "OperationType")
    sale = OperationType.objects.filter(code="sale").first()
    DocType.objects.filter(operation_type__isnull=True).update(operation_type=sale)


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0014_operation_type_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationdocumenttype",
            name="operation_state",
        ),
        migrations.AddField(
            model_name="validationdocumenttype",
            name="operation_type",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="document_types", to="opportunities.operationtype"),
        ),
        migrations.RunPython(map_operation_type, migrations.RunPython.noop),
    ]
