# Generated by Django 4.2.24 on 2025-11-28

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0015_replace_operation_state_with_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationdocument",
            name="status",
            field=django_fsm.FSMField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")], default="pending", max_length=20, protected=False),
        ),
    ]
