# Generated by Django 4.2.24 on 2025-11-28 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0016_validationdocument_fsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideropportunity',
            name='agent_commission_split',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Fraction (0-1) of commission allocated to the agent.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='provideropportunity',
            name='gross_commission_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Negotiated gross commission percentage with the client.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='seekeropportunity',
            name='agent_commission_split',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Fraction (0-1) of commission allocated to the agent.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='seekeropportunity',
            name='gross_commission_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Negotiated gross commission percentage with the client.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='marketingpackage',
            name='state',
            field=django_fsm.FSMField(choices=[('preparing', 'Preparing'), ('published', 'Published'), ('paused', 'Paused')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='validation',
            name='state',
            field=django_fsm.FSMField(choices=[('preparing', 'Preparing'), ('presented', 'Presented'), ('approved', 'Approved')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationdocumenttype',
            name='operation_type',
            field=models.ForeignKey(blank=True, help_text='Restrict this document requirement to a given operation type; leave blank to apply to all.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_types', to='opportunities.operationtype'),
        ),
    ]
