# Generated by Django 4.2.24 on 2025-11-28 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0017_provideropportunity_agent_commission_split_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideropportunity',
            name='agent_commission_split',
        ),
        migrations.RemoveField(
            model_name='seekeropportunity',
            name='agent_commission_split',
        ),
        migrations.AlterField(
            model_name='provideropportunity',
            name='gross_commission_pct',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Negotiated gross commission expressed as 0-1 (e.g., 0.05 for 5%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='seekeropportunity',
            name='gross_commission_pct',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Negotiated gross commission expressed as 0-1 (e.g., 0.03 for 3%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
