# Generated by Django 4.2.24 on 2025-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0020_enforce_tokkobroker_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekeropportunity',
            name='contract_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seekeropportunity',
            name='listing_kind',
            field=models.CharField(choices=[('exclusive', 'Exclusive'), ('non_exclusive', 'Non-exclusive')], default='non_exclusive', max_length=20),
        ),
    ]
