# Generated by Django 4.2.24 on 2025-11-28 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0028_operation_declared_deed_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='initial_offered_amount',
            field=models.DecimalField(decimal_places=2, help_text='Initial offered amount at operation creation.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
