# Generated by Django 4.2.24 on 2025-12-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0036_contract_end_helptext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationAdditionalDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observations", models.TextField(blank=True)),
                (
                    "document",
                    models.FileField(upload_to="validation_additional_documents/%Y/%m/"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_additional_validation_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_attachments",
                        to="opportunities.validation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "verbose_name": "validation additional document",
                "verbose_name_plural": "validation additional documents",
            },
        ),
    ]
