# Generated by Django 4.2.24 on 2025-12-12 07:17

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0038_validationadditionaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('pending', 'Pending'), ('agreed', 'Agreed'), ('signed', 'Signed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('signed_document', models.FileField(blank=True, help_text='Signed agreement documentation uploaded when transitioning to SIGNED state.', null=True, upload_to='operation_agreements/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('provider_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_agreements', to='opportunities.provideropportunity')),
                ('seeker_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_agreements', to='opportunities.seekeropportunity')),
            ],
            options={
                'verbose_name': 'operation agreement',
                'verbose_name_plural': 'operation agreements',
                'ordering': ('-created_at',),
            },
            bases=(utils.mixins.FSMTransitionMixin, models.Model),
        ),
        migrations.AddField(
            model_name='operation',
            name='agreement',
            field=models.OneToOneField(blank=True, help_text='Link to the signed agreement that created this operation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation', to='opportunities.operationagreement'),
        ),
        migrations.AddConstraint(
            model_name='operationagreement',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['pending', 'agreed'])), fields=('provider_opportunity', 'seeker_opportunity'), name='unique_active_operation_agreement'),
        ),
    ]
