# Generated by Django 4.2.24 on 2025-12-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0039_add_operation_agreement'),
    ]

    operations = [
    ]
