# Generated by Django 4.2.24 on 2025-12-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0040_backfill_operation_agreements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='provider_opportunity',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='seeker_opportunity',
        ),
    ]
