# Generated by Django 4.2.24 on 2025-12-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0041_remove_operation_direct_links'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operation',
            name='opportunities_unique_active_operation',
        ),
        migrations.RemoveField(
            model_name='operationagreement',
            name='signed_document',
        ),
        migrations.AddField(
            model_name='operation',
            name='signed_document',
            field=models.FileField(blank=True, help_text='Signed agreement documentation.', null=True, upload_to='operations/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='agreement',
            field=models.OneToOneField(help_text='Link to the signed agreement that created this operation.', on_delete=django.db.models.deletion.PROTECT, related_name='operation', to='opportunities.operationagreement'),
        ),
    ]
