# Generated by Django 4.2.24 on 2025-12-12 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0042_remove_operation_opportunities_unique_active_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationagreement',
            name='initial_offered_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Initial offer proposed with this agreement (currency of seeker).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
