# Generated by Django 4.2.24 on 2025-12-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0013_providerintention_seekerintention_valuation_and_more'),
        ('opportunities', '0043_operationagreement_initial_offered_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideropportunity',
            name='source_intention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provider_opportunity', to='intentions.providerintention'),
        ),
        migrations.AlterField(
            model_name='seekeropportunity',
            name='source_intention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='seeker_opportunity', to='intentions.seekerintention'),
        ),
    ]
