# Generated by Django 4.2.24 on 2026-01-09 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0045_marketingpackagerevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpackagerevision',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
