# Generated by Django 4.2.24 on 2026-01-09 12:05

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import utils.mixins


def backfill_publications(apps, schema_editor):
    MarketingPackage = apps.get_model('opportunities', 'MarketingPackage')
    MarketingPublication = apps.get_model('opportunities', 'MarketingPublication')

    for pkg in MarketingPackage.objects.all().select_related('opportunity'):
        MarketingPublication.objects.update_or_create(
            opportunity=pkg.opportunity,
            defaults={
                'package': pkg,
                'state': getattr(pkg, 'state', 'preparing'),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0047_inline_marketing_package_revisions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingpackage',
            options={'ordering': ('-is_active', '-version', '-created_at'), 'verbose_name': 'marketing package', 'verbose_name_plural': 'marketing packages'},
        ),
        migrations.CreateModel(
            name='MarketingPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('preparing', 'Preparing'), ('published', 'Published'), ('paused', 'Paused')], default='preparing', max_length=20)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_publication', to='opportunities.provideropportunity')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='opportunities.marketingpackage')),
            ],
            options={
                'verbose_name': 'marketing publication',
                'verbose_name_plural': 'marketing publications',
                'ordering': ('-updated_at',),
            },
            bases=(utils.mixins.FSMTransitionMixin, models.Model),
        ),
        migrations.RunPython(backfill_publications, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='marketingpackage',
            name='state',
        ),
    ]
