# Generated by Django 4.2.24 on 2025-11-14 09:45

from django.db import migrations, models
import django.contrib.contenttypes.models
import django.utils.timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSMStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('state_field', models.CharField(max_length=64)),
                ('from_state', models.CharField(blank=True, max_length=64)),
                ('to_state', models.CharField(max_length=64)),
                ('transition', models.CharField(blank=True, max_length=128)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'FSM state transition',
                'verbose_name_plural': 'FSM state transitions',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='fsmstatetransition',
            index=models.Index(fields=['content_type', 'object_id'], name='utils_fsmst_content_009d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='fsmstatetransition',
            index=models.Index(fields=['state_field'], name='utils_fsmst_state_f_117e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='fsmstatetransition',
            index=models.Index(fields=['occurred_at'], name='utils_fsmst_occurre_f9d0a8_idx'),
        ),
    ]
