# Generated by Django 4.2.24 on 2025-11-28 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsmstatetransition',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsm_state_transitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fsmstatetransition',
            index=models.Index(fields=['actor'], name='utils_fsmst_actor_3f64df_idx'),
        ),
    ]
