# Generated by Django 4.2.24 on 2025-12-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_fsmstatetransition_actor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fsmstatetransition',
            new_name='utils_fsmst_actor_i_96b21b_idx',
            old_name='utils_fsmst_actor_3f64df_idx',
        ),
    ]
